package views.secundarias;

import Controllers.RegistroAgendamentoController;
import DAO.JPAUtil;
import jakarta.persistence.EntityManager;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author igor
 */
public class RegistroAgendamento extends javax.swing.JInternalFrame {
    private final RegistroAgendamentoController controller;
    
    /**
     * Creates new form DadosAgendamentos
     */
    public RegistroAgendamento() {
        initComponents();
        EntityManager em = new JPAUtil().getEntityManager();
        controller = new RegistroAgendamentoController(this,em);
        
        //Dimensiona o frame de todos agendamentos para o centro da tela
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        jDialogTodosAgendamentos.setBounds((screenSize.width-460)/2,(screenSize.height-380)/2, 460, 380);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogTodosAgendamentos = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPaneClientes1 = new javax.swing.JScrollPane();
        tabelaTodosAgendamentos = new javax.swing.JTable();
        lblTodosAgendamentos = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jScrollPaneClientes = new javax.swing.JScrollPane();
        tabelaAgendamentos = new javax.swing.JTable();
        btnAtualizar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        lblFinalizado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtCliente = new javax.swing.JTextField();
        txtHorario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacao = new javax.swing.JTextArea();
        lblTotalAgendamentos = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbxServico = new javax.swing.JComboBox<>();
        btnLimparCampos = new javax.swing.JButton();
        btnTodosAgendamentos = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnFinalizarAgendamento = new javax.swing.JButton();
        cbFinalizado = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();

        jDialogTodosAgendamentos.setMinimumSize(new java.awt.Dimension(700, 500));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Todos os Agendamentos");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 8, 310, 40));

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 93, 42));

        tabelaTodosAgendamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Barbeiro", "Horario", "Finalizado", "Cliente", "Serviço", "Valor", "Observação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaTodosAgendamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaTodosAgendamentosMouseClicked(evt);
            }
        });
        jScrollPaneClientes1.setViewportView(tabelaTodosAgendamentos);

        jPanel2.add(jScrollPaneClientes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 670, 330));

        lblTodosAgendamentos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTodosAgendamentos.setText("Agendamentos: ");
        jPanel2.add(lblTodosAgendamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 170, -1));

        javax.swing.GroupLayout jDialogTodosAgendamentosLayout = new javax.swing.GroupLayout(jDialogTodosAgendamentos.getContentPane());
        jDialogTodosAgendamentos.getContentPane().setLayout(jDialogTodosAgendamentosLayout);
        jDialogTodosAgendamentosLayout.setHorizontalGroup(
            jDialogTodosAgendamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
            .addGroup(jDialogTodosAgendamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogTodosAgendamentosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jDialogTodosAgendamentosLayout.setVerticalGroup(
            jDialogTodosAgendamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
            .addGroup(jDialogTodosAgendamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogTodosAgendamentosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        setClosable(true);
        setIconifiable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblTitulo.setText("Dados Agendamentos");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        tabelaAgendamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Horario", "Cliente", "Finalizado", "Serviço", "Valor", "Observação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaAgendamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaAgendamentosMouseClicked(evt);
            }
        });
        jScrollPaneClientes.setViewportView(tabelaAgendamentos);

        jPanel1.add(jScrollPaneClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 660, 180));

        btnAtualizar.setText("Atualizar");
        btnAtualizar.setEnabled(false);
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 140, 40));

        btnDeletar.setText("Deletar");
        btnDeletar.setEnabled(false);
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 140, 40));

        lblFinalizado.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblFinalizado.setText("Finalizado");
        jPanel1.add(lblFinalizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Cliente:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Serviço:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Horario:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Observação:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        txtId.setEditable(false);
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 30, -1));

        txtCliente.setEditable(false);
        jPanel1.add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 120, -1));
        jPanel1.add(txtHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 120, -1));

        txtObservacao.setColumns(20);
        txtObservacao.setRows(5);
        jScrollPane1.setViewportView(txtObservacao);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 260, 100));

        lblTotalAgendamentos.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblTotalAgendamentos.setText("Agendamentos:");
        lblTotalAgendamentos.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(lblTotalAgendamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 210, 30));
        jPanel1.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 50, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Valor: R$");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));
        jPanel1.add(cbxServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 120, -1));

        btnLimparCampos.setText("Limpar Campos");
        btnLimparCampos.setEnabled(false);
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimparCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 140, 41));

        btnTodosAgendamentos.setText("Todos Agendamentos");
        btnTodosAgendamentos.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btnTodosAgendamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodosAgendamentosActionPerformed(evt);
            }
        });
        jPanel1.add(btnTodosAgendamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 210, 30));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/editaAgendamento.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));

        btnFinalizarAgendamento.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnFinalizarAgendamento.setText("Finalizar Agendamento");
        btnFinalizarAgendamento.setEnabled(false);
        btnFinalizarAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarAgendamentoActionPerformed(evt);
            }
        });
        jPanel1.add(btnFinalizarAgendamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 220, 40));

        cbFinalizado.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cbFinalizado.setToolTipText("");
        cbFinalizado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cbFinalizado.setBorderPainted(true);
        cbFinalizado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cbFinalizado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cbFinalizado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/checkIcon.png"))); // NOI18N
        cbFinalizado.setIconTextGap(5);
        jPanel1.add(cbFinalizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 57, 40, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("ID:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTodosAgendamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosAgendamentosActionPerformed
       jDialogTodosAgendamentos.setVisible(true);
       
    }//GEN-LAST:event_btnTodosAgendamentosActionPerformed

    private void tabelaAgendamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaAgendamentosMouseClicked
        controller.completaDados();
    }//GEN-LAST:event_tabelaAgendamentosMouseClicked

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        controller.editaAgendamento();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        controller.deletaAgendamento();
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed
        controller.limparCampos();
    }//GEN-LAST:event_btnLimparCamposActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jDialogTodosAgendamentos.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabelaTodosAgendamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaTodosAgendamentosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaTodosAgendamentosMouseClicked

    private void btnFinalizarAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarAgendamentoActionPerformed
        controller.finalizarAgendamento();
    }//GEN-LAST:event_btnFinalizarAgendamentoActionPerformed

    public JButton getBtnAtualizar() {
        return btnAtualizar;
    }

    public void setBtnAtualizar(JButton btnAtualizar) {
        this.btnAtualizar = btnAtualizar;
    }

    public JButton getBtnDeletar() {
        return btnDeletar;
    }

    public void setBtnDeletar(JButton btnDeletar) {
        this.btnDeletar = btnDeletar;
    }

    public JButton getBtnLimparCampos() {
        return btnLimparCampos;
    }

    public void setBtnLimparCampos(JButton btnLimparCampos) {
        this.btnLimparCampos = btnLimparCampos;
    }

    public JButton getBtnTodosAgendamentos() {
        return btnTodosAgendamentos;
    }

    public void setBtnTodosAgendamentos(JButton btnTodosAgendamentos) {
        this.btnTodosAgendamentos = btnTodosAgendamentos;
    }
    
    public JLabel getLblTotalAgendamentos() {
        return lblTotalAgendamentos;
    }

    public void setLblTotalAgendamentos(JLabel lblTotalAgendamentos) {
        this.lblTotalAgendamentos = lblTotalAgendamentos;
    }
    
    public JComboBox<String> getCbxServico() {
        return cbxServico;
    }

    public void setCbxServico(JComboBox<String> cbxServico) {
        this.cbxServico = cbxServico;
    }

    public JTable getTabelaClientes() {
        return tabelaAgendamentos;
    }

    public void setTabelaClientes(JTable tabelaClientes) {
        this.tabelaAgendamentos = tabelaClientes;
    }

    public JTextField getTxtCliente() {
        return txtCliente;
    }

    public void setTxtCliente(JTextField txtCliente) {
        this.txtCliente = txtCliente;
    }

    public JTextField getTxtHorario() {
        return txtHorario;
    }

    public void setTxtHorario(JTextField txtHorario) {
        this.txtHorario = txtHorario;
    }

    public JTextField getTxtId() {
        return txtId;
    }

    public void setTxtId(JTextField txtId) {
        this.txtId = txtId;
    }

    public JTextArea getTxtObservacao() {
        return txtObservacao;
    }

    public void setTxtObservacao(JTextArea txtObservacao) {
        this.txtObservacao = txtObservacao;
    }

    public JTextField getTxtValor() {
        return txtValor;
    }

    public JTable getTabelaTodosAgendamentos() {
        return tabelaTodosAgendamentos;
    }

    public void setTabelaTodosAgendamentos(JTable tabelaTodosAgendamentos) {
        this.tabelaTodosAgendamentos = tabelaTodosAgendamentos;
    }

    public void setTxtValor(JTextField txtValor) {
        this.txtValor = txtValor;
    }

    public JLabel getLblTodosAgendamentos() {
        return lblTodosAgendamentos;
    }

    public JCheckBox getCbFinalizado() {
        return cbFinalizado;
    }

    public void setCbFinalizado(JCheckBox cbFinalizado) {
        this.cbFinalizado = cbFinalizado;
    }

    public JButton getBtnFinalizarAgendamento() {
        return btnFinalizarAgendamento;
    }

    public void setBtnFinalizarAgendamento(JButton btnFinalizarAgendamento) {
        this.btnFinalizarAgendamento = btnFinalizarAgendamento;
    }

    public JLabel getLblFinalizado() {
        return lblFinalizado;
    }

    public void setLblFinalizado(JLabel lblFinalizado) {
        this.lblFinalizado = lblFinalizado;
    }

    public void setLblTodosAgendamentos(JLabel lblTodosAgendamentos) {
        this.lblTodosAgendamentos = lblTodosAgendamentos;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnFinalizarAgendamento;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JButton btnTodosAgendamentos;
    private javax.swing.JCheckBox cbFinalizado;
    private javax.swing.JComboBox<String> cbxServico;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialogTodosAgendamentos;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneClientes;
    private javax.swing.JScrollPane jScrollPaneClientes1;
    private javax.swing.JLabel lblFinalizado;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTodosAgendamentos;
    private javax.swing.JLabel lblTotalAgendamentos;
    private javax.swing.JTable tabelaAgendamentos;
    private javax.swing.JTable tabelaTodosAgendamentos;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtHorario;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextArea txtObservacao;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
