package views.secundarias;

import Controllers.ServicosController;
import DAO.JPAUtil;
import jakarta.persistence.EntityManager;
import java.awt.CardLayout;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author igor
 */
public class Servicos extends javax.swing.JInternalFrame {
        private final ServicosController controller;
    /**
     * Creates new form Servicos
     */
    public Servicos() {
        initComponents();
        
        EntityManager em = new JPAUtil().getEntityManager();
        controller = new ServicosController(this,em);
        
        controller.atualizaServicos();
        card.add(editarServico,"editarServico");
        card.add(novoServico,"novoServico");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        card = new javax.swing.JPanel();
        editarServico = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbxServico = new javax.swing.JComboBox<>();
        txtValor = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnNovoServico = new javax.swing.JButton();
        lblIcone2 = new javax.swing.JLabel();
        novoServico = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtValorNovoServico = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        txtNomeServico = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();

        setClosable(true);
        setMinimumSize(new java.awt.Dimension(470, 400));
        setPreferredSize(new java.awt.Dimension(500, 450));

        card.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        card.setMinimumSize(new java.awt.Dimension(470, 400));
        card.setPreferredSize(new java.awt.Dimension(470, 400));
        card.setLayout(new java.awt.CardLayout());

        editarServico.setMinimumSize(new java.awt.Dimension(470, 400));
        editarServico.setPreferredSize(new java.awt.Dimension(470, 400));
        editarServico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setText("Serviços");
        editarServico.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 6, 189, 43));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Serviço:");
        editarServico.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Valor: R$");
        editarServico.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, 30));

        cbxServico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxServicoItemStateChanged(evt);
            }
        });
        editarServico.add(cbxServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 160, -1));
        editarServico.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 60, -1));

        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditar.setText("Editar Valor");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        editarServico.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 110, 40));

        btnDeletar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        editarServico.add(btnDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 110, 40));

        btnNovoServico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNovoServico.setText("Criar Novo Serviço");
        btnNovoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoServicoActionPerformed(evt);
            }
        });
        editarServico.add(btnNovoServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 160, 40));

        lblIcone2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/scissor-comb_40861 (1).png"))); // NOI18N
        editarServico.add(lblIcone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        card.add(editarServico, "card2");

        novoServico.setMinimumSize(new java.awt.Dimension(470, 400));
        novoServico.setPreferredSize(new java.awt.Dimension(470, 400));
        novoServico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel4.setText("Novo Serviço");
        novoServico.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 6, 189, 43));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Serviço:");
        novoServico.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));
        novoServico.add(txtValorNovoServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 60, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Valor: R$");
        novoServico.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        btnAdicionar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        novoServico.add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 110, 40));

        txtNomeServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeServicoActionPerformed(evt);
            }
        });
        novoServico.add(txtNomeServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 150, -1));

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        novoServico.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 110, 40));

        card.add(novoServico, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeServicoActionPerformed

    private void btnNovoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoServicoActionPerformed
        CardLayout cardLayout = (CardLayout) card.getLayout();
        cardLayout.show(card,"novoServico");
    }//GEN-LAST:event_btnNovoServicoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        CardLayout cardLayout = (CardLayout) card.getLayout();
        cardLayout.show(card,"editarServico");
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void cbxServicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxServicoItemStateChanged
        controller.atualizaValorServico();
    }//GEN-LAST:event_cbxServicoItemStateChanged

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        controller.novoServico();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        controller.deletaServico();
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        controller.editaValor();
    }//GEN-LAST:event_btnEditarActionPerformed

    public JComboBox<String> getCbxServico() {
        return cbxServico;
    }

    public void setCbxServico(JComboBox<String> cbxServico) {
        this.cbxServico = cbxServico;
    }

    public JTextField getTxtNomeServico() {
        return txtNomeServico;
    }

    public void setTxtNomeServico(JTextField txtNomeServico) {
        this.txtNomeServico = txtNomeServico;
    }

    public JTextField getTxtValor() {
        return txtValor;
    }

    public void setTxtValor(JTextField txtValor) {
        this.txtValor = txtValor;
    }

    public JTextField getTxtValorNovoServico() {
        return txtValorNovoServico;
    }

    public void setTxtValorNovoServico(JTextField txtValorNovoServico) {
        this.txtValorNovoServico = txtValorNovoServico;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNovoServico;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel card;
    private javax.swing.JComboBox<String> cbxServico;
    private javax.swing.JPanel editarServico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblIcone2;
    private javax.swing.JPanel novoServico;
    private javax.swing.JTextField txtNomeServico;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtValorNovoServico;
    // End of variables declaration//GEN-END:variables
}
