package views;

import Controllers.MenuController;
import views.secundarias.NovoAgendamento;
import views.secundarias.CadastroCliente;
import views.secundarias.DadosCliente;
import java.awt.Image;
import java.awt.Graphics;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import views.secundarias.RegistroAgendamento;
import views.secundarias.EditaUsuario;
import views.secundarias.Servicos;

/**
 *
 * @author Igor
 */
public class Menu extends javax.swing.JFrame {
    private final MenuController controller;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        controller = new MenuController(this);
        
        //Dimensiona o frame principal para o centro da tela
        this.setLocation(((Toolkit.getDefaultToolkit().getScreenSize().width  / 2) - (this.getWidth() / 2)), 
                ((Toolkit.getDefaultToolkit().getScreenSize().height / 2) - (this.getHeight() / 2)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        // Adicionar fundo ao jDesktop
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagens/FundoMenu.jpg"));
        Image image = icon.getImage();
        jDesktop = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        panelAgendamentos = new javax.swing.JPanel();
        tituloAgendamentos = new javax.swing.JLabel();
        btnAdicionarAgendamentos = new javax.swing.JButton();
        btnRegistroAgendamentos = new javax.swing.JButton();
        panelClientes = new javax.swing.JPanel();
        tituloCliente = new javax.swing.JLabel();
        btnAdicionarClientes = new javax.swing.JButton();
        btnRegistroClientes = new javax.swing.JButton();
        panelServicos = new javax.swing.JPanel();
        tituloServicos = new javax.swing.JLabel();
        btnEditarServicos = new javax.swing.JButton();
        PanelUsuario = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        lblUsuarioLogado = new javax.swing.JLabel();
        lblDataAtual = new javax.swing.JLabel();
        panelLogo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNivelAcesso = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuClientes = new javax.swing.JMenu();
        menuClientesNovo = new javax.swing.JMenuItem();
        menuDadosClientes = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenu();
        menuNovoUsuario = new javax.swing.JMenuItem();
        menuEditaUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(840, 600));

        panelAgendamentos.setOpaque(false);

        tituloAgendamentos.setBackground(new java.awt.Color(187, 187, 187));
        tituloAgendamentos.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        tituloAgendamentos.setForeground(new java.awt.Color(204, 204, 204));
        tituloAgendamentos.setText("Agendamentos");

        btnAdicionarAgendamentos.setBackground(java.awt.Color.darkGray);
        btnAdicionarAgendamentos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdicionarAgendamentos.setForeground(new java.awt.Color(204, 204, 204));
        btnAdicionarAgendamentos.setText("Adicionar");
        btnAdicionarAgendamentos.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnAdicionarAgendamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarAgendamentosActionPerformed(evt);
            }
        });

        btnRegistroAgendamentos.setBackground(java.awt.Color.darkGray);
        btnRegistroAgendamentos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistroAgendamentos.setForeground(new java.awt.Color(204, 204, 204));
        btnRegistroAgendamentos.setText("Registros");
        btnRegistroAgendamentos.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnRegistroAgendamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroAgendamentosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAgendamentosLayout = new javax.swing.GroupLayout(panelAgendamentos);
        panelAgendamentos.setLayout(panelAgendamentosLayout);
        panelAgendamentosLayout.setHorizontalGroup(
            panelAgendamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgendamentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAgendamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAgendamentosLayout.createSequentialGroup()
                        .addComponent(tituloAgendamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelAgendamentosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdicionarAgendamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRegistroAgendamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
        );
        panelAgendamentosLayout.setVerticalGroup(
            panelAgendamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgendamentosLayout.createSequentialGroup()
                .addComponent(tituloAgendamentos)
                .addGap(12, 12, 12)
                .addGroup(panelAgendamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarAgendamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistroAgendamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panelClientes.setOpaque(false);

        tituloCliente.setBackground(new java.awt.Color(187, 187, 187));
        tituloCliente.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        tituloCliente.setForeground(new java.awt.Color(204, 204, 204));
        tituloCliente.setText("Clientes");

        btnAdicionarClientes.setBackground(java.awt.Color.darkGray);
        btnAdicionarClientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdicionarClientes.setForeground(new java.awt.Color(204, 204, 204));
        btnAdicionarClientes.setText("Adicionar");
        btnAdicionarClientes.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnAdicionarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarClientesActionPerformed(evt);
            }
        });

        btnRegistroClientes.setBackground(java.awt.Color.darkGray);
        btnRegistroClientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistroClientes.setForeground(new java.awt.Color(204, 204, 204));
        btnRegistroClientes.setText("Registros");
        btnRegistroClientes.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnRegistroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelClientesLayout = new javax.swing.GroupLayout(panelClientes);
        panelClientes.setLayout(panelClientesLayout);
        panelClientesLayout.setHorizontalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addComponent(tituloCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdicionarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRegistroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
        );
        panelClientesLayout.setVerticalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addComponent(tituloCliente)
                .addGap(12, 12, 12)
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        panelServicos.setOpaque(false);

        tituloServicos.setBackground(new java.awt.Color(187, 187, 187));
        tituloServicos.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        tituloServicos.setForeground(new java.awt.Color(204, 204, 204));
        tituloServicos.setText("Serviços");

        btnEditarServicos.setBackground(java.awt.Color.darkGray);
        btnEditarServicos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditarServicos.setForeground(new java.awt.Color(204, 204, 204));
        btnEditarServicos.setText("Editar");
        btnEditarServicos.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnEditarServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarServicosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelServicosLayout = new javax.swing.GroupLayout(panelServicos);
        panelServicos.setLayout(panelServicosLayout);
        panelServicosLayout.setHorizontalGroup(
            panelServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelServicosLayout.createSequentialGroup()
                .addGroup(panelServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelServicosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tituloServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelServicosLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(btnEditarServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        panelServicosLayout.setVerticalGroup(
            panelServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelServicosLayout.createSequentialGroup()
                .addComponent(tituloServicos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jDesktop.setLayer(panelAgendamentos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktop.setLayer(panelClientes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktop.setLayer(panelServicos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopLayout = new javax.swing.GroupLayout(jDesktop);
        jDesktop.setLayout(jDesktopLayout);
        jDesktopLayout.setHorizontalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelServicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAgendamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopLayout.setVerticalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(panelAgendamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(panelClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(panelServicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        PanelUsuario.setBackground(new java.awt.Color(51, 51, 51));
        PanelUsuario.setMaximumSize(new java.awt.Dimension(32767, 700));

        btnLogout.setBackground(new java.awt.Color(51, 51, 51));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(204, 204, 204));
        btnLogout.setText("Logout");
        btnLogout.setBorder(null);
        btnLogout.setFocusPainted(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblUsuarioLogado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsuarioLogado.setForeground(new java.awt.Color(204, 204, 204));
        lblUsuarioLogado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuarioLogado.setText("\"Nome Usuario\"");
        lblUsuarioLogado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblDataAtual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDataAtual.setForeground(new java.awt.Color(204, 204, 204));
        lblDataAtual.setText("\"Data Atual\"");

        panelLogo.setBackground(new java.awt.Color(51, 51, 51));
        panelLogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/logoIcone.png"))); // NOI18N
        panelLogo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 80));

        lblNivelAcesso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNivelAcesso.setForeground(new java.awt.Color(204, 204, 204));
        lblNivelAcesso.setText("\"Nivel Acesso\"");

        javax.swing.GroupLayout PanelUsuarioLayout = new javax.swing.GroupLayout(PanelUsuario);
        PanelUsuario.setLayout(PanelUsuarioLayout);
        PanelUsuarioLayout.setHorizontalGroup(
            PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUsuarioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDataAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 71, Short.MAX_VALUE)
                .addComponent(lblUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(lblNivelAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        PanelUsuarioLayout.setVerticalGroup(
            PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(PanelUsuarioLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataAtual)
                    .addComponent(lblUsuarioLogado)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNivelAcesso))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuClientes.setText("Clientes");

        menuClientesNovo.setText("Novo Cliente");
        menuClientesNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesNovoActionPerformed(evt);
            }
        });
        menuClientes.add(menuClientesNovo);

        menuDadosClientes.setText("Dados");
        menuDadosClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDadosClientesActionPerformed(evt);
            }
        });
        menuClientes.add(menuDadosClientes);

        jMenuBar1.add(menuClientes);

        menuUsuarios.setText("Usuários");

        menuNovoUsuario.setText("Novo Usuário");
        menuNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovoUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(menuNovoUsuario);

        menuEditaUsuario.setText("Editar Usuário");
        menuEditaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditaUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(menuEditaUsuario);

        jMenuBar1.add(menuUsuarios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktop)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuClientesNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesNovoActionPerformed
        CadastroCliente cadastroCliente = new CadastroCliente();
        cadastroCliente.setVisible(true);
        jDesktop.add(cadastroCliente);
    }//GEN-LAST:event_menuClientesNovoActionPerformed

    private void menuDadosClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDadosClientesActionPerformed
        DadosCliente pesquisaCliente = new DadosCliente();
        pesquisaCliente.setVisible(true);
        jDesktop.add(pesquisaCliente);
    }//GEN-LAST:event_menuDadosClientesActionPerformed

    private void btnAdicionarAgendamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarAgendamentosActionPerformed
        NovoAgendamento agendamento = new NovoAgendamento();
        agendamento.setVisible(true);
        jDesktop.add(agendamento);
    }//GEN-LAST:event_btnAdicionarAgendamentosActionPerformed

    private void btnRegistroAgendamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroAgendamentosActionPerformed
        RegistroAgendamento dadosAgendamentos = new RegistroAgendamento();
        dadosAgendamentos.setVisible(true);
        jDesktop.add(dadosAgendamentos);
    }//GEN-LAST:event_btnRegistroAgendamentosActionPerformed

    private void btnAdicionarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarClientesActionPerformed
        CadastroCliente cadastroCliente = new CadastroCliente();
        cadastroCliente.setVisible(true);
        jDesktop.add(cadastroCliente);
    }//GEN-LAST:event_btnAdicionarClientesActionPerformed

    private void btnRegistroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroClientesActionPerformed
        DadosCliente pesquisaCliente = new DadosCliente();
        pesquisaCliente.setVisible(true);
        jDesktop.add(pesquisaCliente);
    }//GEN-LAST:event_btnRegistroClientesActionPerformed

    private void btnEditarServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarServicosActionPerformed
        Servicos servicos = new Servicos();
        servicos.setVisible(true);
        jDesktop.add(servicos);
        
    }//GEN-LAST:event_btnEditarServicosActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void menuNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovoUsuarioActionPerformed
        controller.controleAcessoNovoUsuario();
    }//GEN-LAST:event_menuNovoUsuarioActionPerformed

    private void menuEditaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditaUsuarioActionPerformed
        EditaUsuario editaUsuario = new EditaUsuario();
        editaUsuario.setVisible(true);
        jDesktop.add(editaUsuario);
    }//GEN-LAST:event_menuEditaUsuarioActionPerformed

    public JLabel getLblDataAtual() {
        return lblDataAtual;
    }

    public void setLblDataAtual(JLabel lblDataAtual) {
        this.lblDataAtual = lblDataAtual;
    }

    public JLabel getLblUsuarioLogado() {
        return lblUsuarioLogado;
    }

    public void setLblUsuarioLogado(JLabel lblUsuarioLogado) {
        this.lblUsuarioLogado = lblUsuarioLogado;
    }

    public JLabel getLblNivelAcesso() {
        return lblNivelAcesso;
    }

    public void setLblNivelAcesso(JLabel lblNivelAcesso) {
        this.lblNivelAcesso = lblNivelAcesso;
    }

    public JMenuItem getMenuNovoUsuario() {
        return menuNovoUsuario;
    }

    public void setMenuNovoUsuario(JMenuItem menuNovoUsuario) {
        this.menuNovoUsuario = menuNovoUsuario;
    }

    public JDesktopPane getjDesktop() {
        return jDesktop;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelUsuario;
    private javax.swing.JButton btnAdicionarAgendamentos;
    private javax.swing.JButton btnAdicionarClientes;
    private javax.swing.JButton btnEditarServicos;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRegistroAgendamentos;
    private javax.swing.JButton btnRegistroClientes;
    private javax.swing.JDesktopPane jDesktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblDataAtual;
    private javax.swing.JLabel lblNivelAcesso;
    private javax.swing.JLabel lblUsuarioLogado;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenuItem menuClientesNovo;
    private javax.swing.JMenuItem menuDadosClientes;
    private javax.swing.JMenuItem menuEditaUsuario;
    private javax.swing.JMenuItem menuNovoUsuario;
    private javax.swing.JMenu menuUsuarios;
    private javax.swing.JPanel panelAgendamentos;
    private javax.swing.JPanel panelClientes;
    private javax.swing.JPanel panelLogo;
    private javax.swing.JPanel panelServicos;
    private javax.swing.JLabel tituloAgendamentos;
    private javax.swing.JLabel tituloCliente;
    private javax.swing.JLabel tituloServicos;
    // End of variables declaration//GEN-END:variables
}
